version: "3.9"

services:
  backend:
    build: ./backend
    container_name: game-of-life-backend
    expose:
      - "8080"
    networks:
      - proxy

  frontend:
    build: ./frontend
    container_name: game-of-life-frontend
    networks:
      - proxy

networks:
  proxy:
    external: true